version: '3.8'

services:
  app:
    build: ./
    container_name: api-publicidades
    volumes:
      - ./app:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: publicidades
      POSTGRES_USER: embras
      POSTGRES_PASSWORD: wildfire
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
